/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/
import { UiLanguage } from "./types";

export const translations = {
  pt: {
    header: {
      subtitle: "Fabio Arieira - Dev Full Stack",
      apiKey: "Chave API",
      uiLangLabel: "Idioma da Interface"
    },
    intro: {
      tagline: "Conhecimento. Visualizado.",
      badge: "Agora com Google Search Grounding",
      button: "INICIALIZAR SISTEMA",
      skip: "Pular Intro"
    },
    hero: {
      tag: "Explore história, ciência e muito mais.",
      title1: "Visualize",
      title2: "O Desconhecido.",
      desc: "Gere diagramas e infográficos com tecnologia Google."
    },
    search: {
      placeholder: "O que você quer visualizar?",
      audience: "Público",
      style: "Estética",
      language: "Idioma do Conteúdo",
      button: "INICIAR",
      format: "Formato 16:9"
    },
    loading: {
      connecting: "Estabelecendo conexão...",
      researching: "Pesquisando tópico...",
      designing: "Projetando Infográfico...",
      processing: "Processando modificação...",
      flying: {
        history: "HISTÓRIA",
        science: "CIÊNCIA",
        facts: "FATOS",
        data: "DADOS"
      }
    },
    results: {
      title: "Fontes de Pesquisa",
      external: "Fonte Externa"
    },
    article: {
      label: "Artigo Explicativo",
      copy: "Copiar",
      print: "Imprimir / PDF",
      reportTitle: "Relatório Científico",
      generatedBy: "Gerado por IA (Gemini) - Verifique as informações"
    },
    infographic: {
      promptLabel: "COMANDO",
      editPlaceholder: "Refinar o visual (ex: 'Faça o fundo estrelado')...",
      enhance: "Melhorar",
      fullscreen: "Tela Cheia",
      download: "Baixar Imagem"
    },
    history: {
      title: "Arquivos da Sessão"
    },
    apiModal: {
      title: "Gerenciar Chaves API",
      desc: "Configure suas credenciais do Google Gemini.",
      rotationTitle: "Rotação Automática",
      rotationDesc: "Você pode inserir múltiplas chaves (uma por linha). Se uma chave atingir o limite de cota, o sistema tentará a próxima automaticamente.",
      label: "Chaves API do Gemini",
      placeholder: "Ex: AIzaSy...\nAIzaSy...\n(Deixe em branco para usar a conta conectada padrão)",
      save: "Salvar Chaves",
      note: "Suas chaves são salvas localmente no navegador e nunca enviadas a servidores externos (exceto Google API).",
      connect: "Conectar Chave API"
    },
    errors: {
      topicRequired: "Por favor, digite um tópico para visualizar.",
      quota: "Erro de cota ou permissão. Tente adicionar/rotacionar chaves API.",
      generic: "O serviço de geração de imagem está temporariamente indisponível. Tente novamente.",
      accessDenied: "Acesso negado. Verifique suas chaves API.",
      modFailed: "Falha na modificação. Tente um comando diferente."
    },
    options: {
      levels: {
        Elementary: "Ensino Fundamental",
        HighSchool: "Ensino Médio",
        College: "Universitário",
        Expert: "Especialista"
      },
      styles: {
        Default: "Padrão Científico",
        Minimalist: "Minimalista",
        Realistic: "Fotorealista",
        Cartoon: "Cartoon/HQ",
        Vintage: "Vintage",
        Futuristic: "Futurista HUD",
        ThreeDRender: "Render 3D", // Key slightly changed to match usage if needed, but '3D Render' maps to this
        Sketch: "Esboço Técnico"
      }
    }
  },
  en: {
    header: {
      subtitle: "Fabio Arieira - Full Stack Dev",
      apiKey: "API Key",
      uiLangLabel: "Interface Language"
    },
    intro: {
      tagline: "Knowledge. Visualized.",
      badge: "Now with Google Search Grounding",
      button: "INITIALIZE SYSTEM",
      skip: "Skip Intro"
    },
    hero: {
      tag: "Explore history, science, and more.",
      title1: "Visualize",
      title2: "The Unknown.",
      desc: "Generate diagrams and infographics powered by Google."
    },
    search: {
      placeholder: "What do you want to visualize?",
      audience: "Audience",
      style: "Aesthetic",
      language: "Content Language",
      button: "START",
      format: "16:9 Format"
    },
    loading: {
      connecting: "Establishing connection...",
      researching: "Researching topic...",
      designing: "Designing Infographic...",
      processing: "Processing modification...",
      flying: {
        history: "HISTORY",
        science: "SCIENCE",
        facts: "FACTS",
        data: "DATA"
      }
    },
    results: {
      title: "Research Sources",
      external: "External Source"
    },
    article: {
      label: "Explanatory Article",
      copy: "Copy",
      print: "Print / PDF",
      reportTitle: "Scientific Report",
      generatedBy: "Generated by AI (Gemini) - Verify information"
    },
    infographic: {
      promptLabel: "PROMPT",
      editPlaceholder: "Refine visuals (e.g., 'Make the background starry')...",
      enhance: "Enhance",
      fullscreen: "Fullscreen",
      download: "Download Image"
    },
    history: {
      title: "Session Archives"
    },
    apiModal: {
      title: "Manage API Keys",
      desc: "Configure your Google Gemini credentials.",
      rotationTitle: "Automatic Rotation",
      rotationDesc: "You can enter multiple keys (one per line). If a key reaches its quota limit, the system will automatically try the next one.",
      label: "Gemini API Keys",
      placeholder: "Ex: AIzaSy...\nAIzaSy...\n(Leave blank to use the default connected account)",
      save: "Save Keys",
      note: "Your keys are saved locally in the browser and never sent to external servers (except Google API).",
      connect: "Connect API Key"
    },
    errors: {
      topicRequired: "Please enter a topic to visualize.",
      quota: "Quota or permission error. Try adding/rotating API keys.",
      generic: "Image generation service is temporarily unavailable. Please try again.",
      accessDenied: "Access denied. Check your API keys.",
      modFailed: "Modification failed. Try a different command."
    },
    options: {
      levels: {
        Elementary: "Elementary",
        HighSchool: "High School",
        College: "University",
        Expert: "Expert"
      },
      styles: {
        Default: "Scientific Standard",
        Minimalist: "Minimalist",
        Realistic: "Photorealistic",
        Cartoon: "Cartoon/Comic",
        Vintage: "Vintage",
        Futuristic: "Futuristic HUD",
        ThreeDRender: "3D Render",
        Sketch: "Technical Sketch"
      }
    }
  },
  es: {
    header: {
      subtitle: "Fabio Arieira - Dev Full Stack",
      apiKey: "Clave API",
      uiLangLabel: "Idioma de Interfaz"
    },
    intro: {
      tagline: "Conocimiento. Visualizado.",
      badge: "Ahora con Google Search Grounding",
      button: "INICIALIZAR SISTEMA",
      skip: "Saltar Intro"
    },
    hero: {
      tag: "Explora historia, ciencia y más.",
      title1: "Visualiza",
      title2: "Lo Desconocido.",
      desc: "Genera diagramas e infografías con tecnología Google."
    },
    search: {
      placeholder: "¿Qué quieres visualizar?",
      audience: "Audiencia",
      style: "Estética",
      language: "Idioma del Contenido",
      button: "INICIAR",
      format: "Formato 16:9"
    },
    loading: {
      connecting: "Estableciendo conexión...",
      researching: "Investigando tema...",
      designing: "Diseñando Infografía...",
      processing: "Procesando modificación...",
      flying: {
        history: "HISTORIA",
        science: "CIENCIA",
        facts: "HECHOS",
        data: "DATOS"
      }
    },
    results: {
      title: "Fuentes de Investigación",
      external: "Fuente Externa"
    },
    article: {
      label: "Artículo Explicativo",
      copy: "Copiar",
      print: "Imprimir / PDF",
      reportTitle: "Informe Científico",
      generatedBy: "Generado por IA (Gemini) - Verifique la información"
    },
    infographic: {
      promptLabel: "COMANDO",
      editPlaceholder: "Refinar visuales (ej: 'Haz el fondo estrellado')...",
      enhance: "Mejorar",
      fullscreen: "Pantalla Completa",
      download: "Descargar Imagen"
    },
    history: {
      title: "Archivos de Sesión"
    },
    apiModal: {
      title: "Gestionar Claves API",
      desc: "Configura tus credenciales de Google Gemini.",
      rotationTitle: "Rotación Automática",
      rotationDesc: "Puedes ingresar múltiples claves (una por línea). Si una clave alcanza el límite de cuota, el sistema probará automáticamente la siguiente.",
      label: "Claves API de Gemini",
      placeholder: "Ej: AIzaSy...\nAIzaSy...\n(Dejar en blanco para usar la cuenta conectada predeterminada)",
      save: "Guardar Claves",
      note: "Tus claves se guardan localmente en el navegador y nunca se envían a servidores externos (excepto Google API).",
      connect: "Conectar Clave API"
    },
    errors: {
      topicRequired: "Por favor, ingresa un tema para visualizar.",
      quota: "Error de cuota o permiso. Intenta agregar/rotar claves API.",
      generic: "El servicio de generación de imágenes no está disponible temporalmente. Inténtalo de nuevo.",
      accessDenied: "Acceso denegado. Verifica tus claves API.",
      modFailed: "Falló la modificación. Prueba un comando diferente."
    },
    options: {
      levels: {
        Elementary: "Primaria",
        HighSchool: "Secundaria",
        College: "Universitario",
        Expert: "Experto"
      },
      styles: {
        Default: "Estándar Científico",
        Minimalist: "Minimalista",
        Realistic: "Fotorrealista",
        Cartoon: "Cartoon/Cómic",
        Vintage: "Vintage",
        Futuristic: "Futurista HUD",
        ThreeDRender: "Render 3D",
        Sketch: "Boceto Técnico"
      }
    }
  }
};